container_image_default="registry.fedoraproject.org/fedora-toolbox:42"
container_name_default="toolbox"
container_pre_init_hook='export SHELL="~/.nix-profile/bin/fish"; source ~/.config/distrobox/nix.sh preinit'
container_init_hook='export SHELL="~/.nix-profile/bin/fish"; source ~/.config/distrobox/nix.sh init'
