# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: goose
description: givens own operating system experiment

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    no-cache: true
    files:
      - source: system
        destination: /

  - type: akmods
    no-cache: true
    base: main
    install:
      - framework-laptop

  - type: initramfs
    no-cache: true

  - from-file: ../modules/00-system.yml
  - from-file: ../modules/01-atomic.yml
  - from-file: ../modules/02-desktop.yml
  - from-file: ../modules/03-cli.yml

  - type: justfiles
    no-cache: true
    install: true
    validate: true

  # Bootstrap image
  - type: copy
    no-cache: true
    src: ../
    dest: /opt/goose

  - type: signing
    no-cache: true
