# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: goose
description: given's own operating system experiment

base-image: ghcr.io/ublue-os/base-main
image-version: 42

modules:
  - type: script
    scripts:
      - dnf.sh

  - from-file: ../modules/00-system.yml
  - from-file: ../modules/01-atomic.yml
  - from-file: ../modules/02-desktop.yml
  - from-file: ../modules/03-cli.yml

  - type: akmods
    base: main
    install:
      - framework-laptop

  # Regenerate initramfs; must follow akmods
  - type: initramfs
    no-cache: true

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - dnf.sh

  - type: signing
    no-cache: true
