unqualified-search-registries = ["docker.io", "ghcr.io", "quay.io"]

[[registry]]
location = "ghcr.io/givensuman"
prefix = "ghcr.io/givensuman"
insecure = false
blocked = false

[[registry.mirror]]
location = "ghcr.io/givensuman"
